### ISSUE TITLE
Nose Timer doesn't work with multiprocess

### ISSUE THREAD

**Issue by rsnyman** [mahmoudimus/nose-timer#31]
In order to run my tests faster, I use the multiprocess module and run my tests in parallel, like so:

```
$ nosetests ... --processes=4
```

When I try to run my tests with Nose Timer, I don't see any timer results:

```
$ nosetests ... --processes=4 --with-timer
```

It works fine when I drop "--processes=4"

**Comment by ewyler** [comment]
FYI it appears this functionality was broken by https://github.com/mahmoudimus/nose-timer/commit/dd1b9418517d75c21b9213101789cb33a76749c0. There are test timings printed, but they're wrong and aren't printed until after all the tests have run.

**Comment by mahmoudimus** [comment]
@ewyler how are you running your tests?

**Comment by ewyler** [comment]
Yup! OS is Ubuntu 14.04.3 LTS, Python 2.7.6, the tests are being executed by running a command as specified at the start of this issue. Adding --processes=(anything) to the command causes the timings to be at the end and screwed up. If I remove that, it all works great. I switched us back to using 0.4.4 in the meantime as that still works.

**Comment by mahmoudimus** [comment]
@ewyler so this is for the 0.5.0 release? Ok, thanks. I will link this report w/ #68

**Comment by ewyler** [comment]
Yes, 0.5.0, should've included the version. Thanks, appreciate the prompt response
