### ISSUE TITLE
Timer options

### ISSUE THREAD

**Issue by skudriashev** [mahmoudimus/nose-timer#36]
Guys, currently I see a problem with using the `--timer-ok` and `--timer-warning` options.
When the `--timer-ok` option is used it is expected that all tests which take less time than `--timer-ok` will be highlighted in green. The same with `--timer-warning`. But let's imagine somebody used the `--timer-warning` option only with value < 1s and expects to see all tests that took less time than `--timer-warning` in yellow, other - in red. But this will never happen, since all tests passed **less** then the `--timer-ok` (which is 1s by default) and they are marked as 'ok'. Yes, this a bit confusing.

I would propose to treat  these option as **thresholds** of maximum pass time and use the `--timer-error` and `--time-warning` options. So the `--timer-error` will color all tests with red, if test took **more** time then specified threshold. The same with `--time-warning`. I think this is more natural (maybe I wrong). 

Moreover, to prevent situations when these options intersect I think in case when at least one threshold specified - the default values should not be taken into account.

Folks, what are your thoughts?

**Comment by mahmoudimus** [comment]
@skudriashev haven't forgotten about this, been a few busy days. hope you had a great new years!

**Comment by skudriashev** [comment]
@mahmoudimus hope you too :)

**Comment by mahmoudimus** [comment]
@skudriashev I think #66 and https://github.com/mahmoudimus/nose-timer/commit/72a3d5af71808d5d234ab051abde5ff7bd89055a are actually related to this issue (somewhat).
