### ISSUE TITLE
PyPy3 and Python 3.2 timeout and error builds

### ISSUE THREAD

**Issue by hugovk** [mahmoudimus/nose-timer#51]
```
$ coverage run --append --include=PIL/* -m nose -vx Tests/test_*.py --with-timer --timer-top-n 10 --timer-ok 1s --timer-warning 10s
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

See https://travis-ci.org/hugovk/nose-timer/builds/42836302 and https://travis-ci.org/mahmoudimus/nose-timer/builds/42836459

This prevents nose-timer being used on projects which need to support PyPy3 and Python 3.2.

**Comment by hugovk** [comment]
@skudriashev Any chance of a new release of nose-timer to include these fixes? 

Version 0.4.3 on PyPI still hangs:
https://travis-ci.org/hugovk/Pillow/builds/61051050

But the git version passes:
https://travis-ci.org/hugovk/Pillow/builds/61215260

Thank you!

**Comment by skudriashev** [comment]
@hugovk Could you, please, give me an example of how to reproduce the behavior? Without coverage, just nose command, so I can look into this.

**Comment by hugovk** [comment]
@skudriashev No need to look into it, just release :)

The latest master passes with the fixes made ion Dec 8, 2014, but the last (four) releases were on 2 Dec 2014.

**Comment by mahmoudimus** [comment]
To release, just git tag and push and we should automatically get a publish
on pypi

- Mahmoud

**Comment by skudriashev** [comment]
@hugovk new version released, please check.

**Comment by hugovk** [comment]
I've rebuilt https://travis-ci.org/hugovk/Pillow/builds/61051050 and PyPy3 and Python 3.2 now pass.

Thank you!
