### ISSUE TITLE
Write time-statistics to file

### ISSUE THREAD

**Issue by PureW** [mahmoudimus/nose-timer#57]
I would like to save statistics on file to be able to spot potential regressions performance-wise. Could some option be added to save a machine-readable format of the data nose-timer produces?

**Comment by skudriashev** [comment]
@PureW please, consider thread #13, this might be what you need.

**Comment by PureW** [comment]
@skudriashev Ahh that seems perfect. Thanks for that!

**Comment by skudriashev** [comment]
@PureW NP:)
