### ISSUE TITLE
port to nose2 plugin?

### ISSUE THREAD

**Issue by cgoldberg** [mahmoudimus/nose-timer#58]
hey guys,
I guess nose2 is the future (is it?)... and it has a revamped plugin system:
https://nose2.readthedocs.org/en/latest/plugins.html

it would be great to get nose-timer ported to work with nose2.  This would most likely be a new project (nose2-timer), based heavily off of nose-timer plugin.

I'm game to work on it along with anyone else who is interested.

any thoughts?

**Comment by skudriashev** [comment]
Hey, +1 from me)

**Comment by skudriashev** [comment]
@mahmoudimus, shall we start new project nose2-timer?

**Comment by skudriashev** [comment]
Closing the issue since this is not really issue.

**Comment by scottgigante** [comment]
Did this ever happen? I don't see anything with a quick Google search.
