### ISSUE TITLE
Unable to import nose-timer 0.4.3

### ISSUE THREAD

**Issue by dresendez** [mahmoudimus/nose-timer#59]
http://stackoverflow.com/questions/28504849/unable-to-load-plugin-nose-timer

downgraded to 0.3.0 and worked fine.  0.4.3 will not run

**Comment by hugovk** [comment]
Version 0.4.3 works for me. What commands are you using, exactly?

**Comment by skudriashev** [comment]
@dresendez And what OS?

**Comment by dresendez** [comment]
I am on OSX Yosemite, and the command i was using (via os.sytem):

    os.system('nosetests %s --with-timer %s --process-timeout=600 --tc-file=%s --verbosity=%s --nologcapture' % (test, xmlout, configfile, (args['verbose'])))

**Comment by dresendez** [comment]
I am on OSX Yosemite, and the command i was using (via os.sytem):

    os.system('nosetests %s --with-timer %s --process-timeout=600 --tc-file=%s --verbosity=%s --nologcapture' % (test, xmlout, configfile, (args['verbose'])))

**Comment by dresendez** [comment]
I didn't mean to close it btw.

**Comment by hugovk** [comment]
What output do you get when you run `pip freeze` on the command line?

Instead of:
```python
os.system('nosetests %s --with-timer %s --process-timeout=600 --tc-file=%s --verbosity=%s --nologcapture' % (test, xmlout, configfile, (args['verbose'])))
```

Can you try:
```python
cmd = 'nosetests %s --with-timer %s --process-timeout=600 --tc-file=%s --verbosity=%s --nologcapture' % (test, xmlout, configfile, (args['verbose']))
print("cmd=" + cmd)
os.system(cmd)
```

And also paste the full output?
