### ISSUE TITLE
Option to show only the tests above the ok/warning threshold

### ISSUE THREAD

**Issue by sprt** [mahmoudimus/nose-timer#66]
It would be nice to be able to filter the tests based on their color.

**Comment by skudriashev** [comment]
@sprt, what you think about having *--filter* (or *--show* or *--show-only*) switch (that would be accumulative) with usage:

    ... --filter ok    # to show green tests
    ... --filter warning    # to show yellow tests
    ... --filter error    # to shown red tests
    ... --filter ok --filter warning    # to show green and yellow tests

@mahmoudimus, what you think about this feature?

**Comment by sprt** [comment]
Yup, sounds good! Maybe allow concatenating too, like `--filter ok,warning`

**Comment by skudriashev** [comment]
@sprt, please, checkout my last commit.

**Comment by sprt** [comment]
Awesome! Thank you! :sparkles:

**Comment by mahmoudimus** [comment]
@skudriashev, looks great! :+1:

**Comment by skudriashev** [comment]
@mahmoudimus thanks! I'll close this issue.

**Comment by mahmoudimus** [comment]
Might be related to issue https://github.com/mahmoudimus/nose-timer/issues/7
