### ISSUE TITLE
v0.5 is broken on MacOs

### ISSUE THREAD

**Issue by dmakhno** [mahmoudimus/nose-timer#68]
https://docs.python.org/2/library/multiprocessing.html#multiprocessing.Queue.qsize
```
Note that this may raise NotImplementedError on Unix platforms like Mac OS X where sem_getvalue() is not implemented.
```

I got
```
  File "/Users/user/Projects/vermilion/venv/lib/python2.7/site-packages/nosetimer/plugin.py", line 96, in report
    for i in range(_results_queue.qsize()):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/queues.py", line 143, in qsize
    return self._maxsize - self._sem._semlock._get_value()
```

It used to work perfectly with multiprocessing and xunitmp with mac, centos and ubuntu, now it fails totally and have to roll back to 0.4.4

**Comment by dmakhno** [comment]
@skudriashev, I cannot contribute to fix, I don't quite understand the [diff](https://github.com/mahmoudimus/nose-timer/compare/v0.4.4...v0.5.0)

**Comment by mahmoudimus** [comment]
@dmakhno I will take a look when I get a chance. Is this blocking you now?

**Comment by dmakhno** [comment]
@mahmoudimus, Thanks... I reverted back to 0.4.4, it works absolutely fine for me since I don't have windows at all, and as I understand support of windows in 0.5 broken this.

**Comment by skudriashev** [comment]
@dmakhno, this change was done to make multiprocessing nose plugin work with timer plugin. There is nothing about Windows.

**Comment by skudriashev** [comment]
@dmakhno, btw, please look the the comment: "# Windows and Python 2.7 multiprocessing don't marry well.", so we need to check that we are not on Windows. Perhaps we need to skip Mac OS too.

**Comment by skudriashev** [comment]
@dmakhno, do you run the nose-timer with multiprocessing plugin?

**Comment by dmakhno** [comment]
@skudriashev, yes, 0.4.4 works just as fine.
Here is jenkins
![image](https://cloud.githubusercontent.com/assets/1913863/11807571/3c417726-a323-11e5-8185-5517b7c34554.png)

These are example integration tests and pretty heavy with timing, but works as a charm. And again 0.4.4.

**Comment by skudriashev** [comment]
@dmakhno, right, you use the multiprocessing plugin. So need to fix. Will do when possible.

**Comment by skudriashev** [comment]
Hi, @dmakhno! I've implemented fix for MacOs in the max-os-fix branch (https://github.com/mahmoudimus/nose-timer/tree/mac-os-fix). Could you, please, try it to check if this fixes your issue. Thanks.

**Comment by matclayton** [comment]
We're seeing the same issue, and this branch fixed it for us, any chance of releasing it to pipy?

**Comment by mahmoudimus** [comment]
@matclayton thanks for the feedback. we've made a pull request here #71 and we'll publish to pypi shortly.

**Comment by mahmoudimus** [comment]
@matclayton can you pull v 0.6.0 from pypi and confirm that it works for you?

**Comment by matclayton** [comment]
Have done, and it does :)

On 11 February 2016 at 19:23, Mahmoud Abdelkader <notifications@github.com>
wrote:

> @matclayton <https://github.com/matclayton> can you pull v 0.6.0 from
> pypi and confirm that it works for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mahmoudimus/nose-timer/issues/68#issuecomment-183020415>
> .
>



-- 
-- 
Matthew Clayton | Co-Founder
Mixcloud Limited

mixcloud http://www.mixcloud.com/mat
twitter http://www.twitter.com/matclayton

email mat@mixcloud.com
mobile +44 7872007851
skype matclayton

**Comment by mahmoudimus** [comment]
@matclayton :+1: thanks for reporting!

@dmakhno you may want to try this as well. let us know how it goes :)
