### ISSUE TITLE
Why BSD 4-Clause?

### ISSUE THREAD

**Issue by jakirkham** [mahmoudimus/nose-timer#72]
Trying to understand why the BSD 4-Clause is present here. It is known that the advertising clause causes [serious problems](http://www.gnu.org/licenses/bsd.en.html). So, I am trying to understand why it was added and whether it can be removed (i.e. the license converted to BSD 3-Clause or similar).

**Comment by mahmoudimus** [comment]
Hmm, my intention was not to make this BSD 4-Clause. It should definitely be either MIT/BSD dual-licensed or Apache 2.0 License. Any preference?

**Comment by jakirkham** [comment]
Not particularly. As long as BSD clauses are less than 4, I am happy.

**Comment by mahmoudimus** [comment]
@skudriashev any preference?

**Comment by skudriashev** [comment]
@mahmoudimus, not really. MIT would be fine I guess.

**Comment by jakirkham** [comment]
Should I submit a PR to make it MIT then?

**Comment by mahmoudimus** [comment]
@jakirkham would appreciate that! alos add yourself to the contributors list please!

**Comment by MrOerni** [comment]
@jakirkham @mahmoudimus 
Is this a thing anymore?

**Comment by e0ne** [comment]
Looks like we're OK to close this issue.

**Comment by jakirkham** [comment]
Why? It doesn't appear to be fixed.

**Comment by jakirkham** [comment]
Please see PR ( https://github.com/mahmoudimus/nose-timer/pull/81 ) for the fix.

**Comment by e0ne** [comment]
@jakirkham I'm sorry, we still have both licenses

**Comment by jakirkham** [comment]
No worries.
