### ISSUE TITLE
Running the test suite with the plugin messes up test case sorting

### ISSUE THREAD

**Issue by DavidCsordas** [mahmoudimus/nose-timer#74]
Running the tests with verbose=3 processes and outputs test cases in alphabetical order. Except when running it with the timer plugin, which messes up this order. It is but a minor annoyance, but an annoyance all the same.

**Comment by skudriashev** [comment]
@DavidCsordas, I wasn't able to reproduce the issue. Could you please specify command you run and the output. Thanks.

**Comment by DavidCsordas** [comment]
--with-timer

Output is non-alphabetical, and there's nothing else specific about it (it is also a commercially owned test suite with hundreds of tests, I'd prefer not to share the output).

**Comment by skudriashev** [comment]
@DavidCsordas, when I run it locally - tests are sorted alphabetically and timer plugin output is sorted by `time`.

**Comment by DavidCsordas** [comment]
@skudriashev Ok, I see, thank you. Can be closed as non-issue.
