### ISSUE TITLE
--timer-json-file option is not available

### ISSUE THREAD

**Issue by peggybear** [mahmoudimus/nose-timer#82]
Hi! I have the latest version `0.6.0`

I'm trying to export my results using the `--timer-json-file` option but then it give me an error
```
Usage: nosetests [options]

nosetests: error: no such option: --timer-json-file
```

The other options `--with-timer` and `--timer-[ok|warning]` works properly for me. Could someone take a look at this?

**Comment by mahmoudimus** [comment]
@peggybear looks like we didn't release the most recent version to pypi. We need to cut a new release. I'll get around to it soon, meanwhile, can you pull from github if that is acceptable? thanks for reporting!

**Comment by skudriashev** [comment]
@mahmoudimus, shall I bump a new version? 0.6.1?

**Comment by mahmoudimus** [comment]
@skudriashev that would be best :) we added a new option, so let's bump to 0.7 :)

**Comment by peggybear** [comment]
@mahmoudimus yes no rush, I can just pull from github! thanks!

**Comment by skudriashev** [comment]
Version updated.
