### ISSUE TITLE
Failing red tests, possibly with exceptions

### ISSUE THREAD

**Issue by dewaldabrie** [mahmoudimus/nose-timer#88]
Hi, 
Thank you for this great plugin, I'm finding it very useful for quality assurance on tests.
I would like to put in a feature request for having an option to fail tests if they exceed the warning threshold. 

In other words, 'red' or 'error' classifications will be failed with an error message like "All the assertions in this test passed, but the test itself was slower than the allowed threshold of <n> seconds". 

Along with this, it would be nice to have the option to pass in the python path of certain tests that should be excluded from failing based on time. For example parameters like 
    --ignore-time-for-test=tests.MyTestClass.test_this --ignore-time-for-test=tests.MyTestClass2.test_this2
This would be useful if we have a good reason why some tests should run for longer than the normal threshold. 

I would be happy to make contributions to implement the above.

**Comment by mahmoudimus** [comment]
@dewaldabrie thanks for the nice comments. If you wanted to take a stab at it, that would be great. See #87 #80 and the various proposals. I'm going to CC @skudriashev for knowledge sharing as well :)
