### ISSUE TITLE
Issue running --with-timer and --process at the same time

### ISSUE THREAD

**Issue by zsolt-sb** [mahmoudimus/nose-timer#90]
Please look at plugin.py line 258

The line
            _results_queue.put((test.id(), time_taken, None))
Should be
            _results_queue.put((test.id(), time_taken, status))

The resulting bug is that timer prints [None] for the status instead of the status.

**Comment by skudriashev** [comment]
@zsolt-sb thanks for reporting this. Should be fixed now.

**Comment by zsolt-sb** [comment]
Wow, thanks for the lightning fast turnaround.  Now I don't have to implement a workaround.
