### ISSUE TITLE
fail to run the tests

### ISSUE THREAD

**Issue by hubutui** [mahmoudimus/nose-timer#93]
here is the output:
```text
tests/test_plugin.py:37: in test_format_report_line
    self.assertEqual(
E   AssertionError: "[err[16 chars]Mock name='test' id='140132806050288'>: 1.0000s" != "[err[16 chars]Mock name='test' id='140132806050288'>: \x1b[31m1.0000s\x1b[0m"
E   - [error] 0.10% <MagicMock name='test' id='140132806050288'>: 1.0000s
E   + [error] 0.10% <MagicMock name='test' id='140132806050288'>: [31m1.0000s[0m
E   ?                                                             +++++       ++++
```
for complete build log, check [python-nose-timer.log](https://github.com/mahmoudimus/nose-timer/files/4335912/python-nose-timer.log).
I'm building this pkg in the latest ArchLinux environment.

**Comment by skudriashev** [comment]
@hubutui did it work before for you?

**Comment by hubutui** [comment]
Yeah, according to the build [history](https://build.archlinuxcn.org/packages/#/python-nose-timer), the test passed in version 0.7.5.

**Comment by skudriashev** [comment]
Here is run on TravisCI: https://travis-ci.org/github/mahmoudimus/nose-timer/jobs/662854089?utm_medium=notification&utm_source=github_status

**Comment by hubutui** [comment]
Hmm, not sure why it failed. Did you test the latest python (3.8.2)?

**Comment by skudriashev** [comment]
@hubutui, no, 3.8.0. Let me try with 3.8.2.

**Comment by skudriashev** [comment]
@hubutui here is run on Python 3.8.2 https://travis-ci.org/github/mahmoudimus/nose-timer/jobs/663120316?utm_medium=notification&utm_source=github_status

**Comment by skudriashev** [comment]
@hubutui could you please provide more details of how you run those tests?

**Comment by hubutui** [comment]
You could reproduce with ArchLinux docker. Here is the [PKGBUILD](https://github.com/mahmoudimus/nose-timer/files/4341359/PKGBUILD.txt) file I use for building pkg in ArchLinux.
1. create a ArchLinux container, `docker run -it archlinux`
2. install deps and necessary pkgs, `pacman -S base-devel wget python-mock python-parameterized python-nose`
3. create a non-root user as we could not run `makepkg` with root user, `useradd -m test`
4. switch to the user, `su -l test`
5. download [PKGBUILD](https://github.com/mahmoudimus/nose-timer/files/4341359/PKGBUILD.txt), and rename it to `PKGBUILD`. github don't let me upload a file without extension suffix.
6. build with: `makepkg`.

If you have ArchLinux in virtualbox, you could simply install `base-devel devtools`, download the `PKGBUILD` file, and run `extra-x86_64-build`, it will create a clean chroot environment, install deps, and build the pkg.

**Comment by skudriashev** [comment]
@hubutui in your installation you need to install one more package: `python-termcolor`. This is required for tests to pass.

**Comment by skudriashev** [comment]
@hubutui closing this issue for now. Feel free to reopen if you have any questions. Thanks!
